apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{Project.Deployment.Name}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: #{Project.Labels.Component}
  template:
    metadata:
      labels:
        component: #{Project.Labels.Component}
    spec:
      containers:
        - name: auditservice
          image: octopussamples/octopub-audit-microservice-mysql:#{Project.Container.Tag}
          ports:
            - name: http-audit
              containerPort: 10000
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: database-password
            - name: DATABASE_HOSTNAME
              value: "#{Octopub.Yaml.Database.Server.Name}"
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_NAME
              value: "#{Octopub.Yaml.Database.Name}"
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: database-user
            - name: MIGRATE_AT_START
              value: "false"
            - name: COGNITO_DISABLE_AUTH
              value: "true" #Comment
